name: Check



on: push



permissions:
  contents: read
  id-token: write



jobs:

  test-JSR:

    runs-on: ubuntu-slim
    timeout-minutes: 3
    strategy:
      matrix:
        deno:
          - ~2.4
          - ^2.5

    steps:

      - name: Setup repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup deno
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: ${{ matrix.deno }}

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno task spec --coverage --quiet --parallel

      - name: Run publish --dry-run
        run: deno publish --dry-run

      - name: Run codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          files: coverage/lcov.info
          use_oidc: true



  test-npm:

    runs-on: ubuntu-slim
    timeout-minutes: 3
    strategy:
      matrix:
        tsc:
          - "5.8.3"
          - "5.9.2"
          - "6.0.3"

    steps:

      - name: Setup repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: v24

      - name: Move package.json
        run: cp tmp-package.json package.json

      - name: Install
        run: npm install --no-{fund,package-lock}

      - name: Build
        run: |-

          rm -r ./src/apps
          npx --yes --package=typescript@${{ matrix.tsc }} tsc

      - name: Bundle
        run: npx --yes esbuild@0.28.0 ./dist/utils.js
                --outfile=./dist/utils.js
                --format=esm
                --allow-overwrite
                --bundle

      - name: Replace
        run: |-

          find ./dist -type f -name '*.js'   -exec perl -i -pe 's/^var /const /g' {} \;
          find ./dist -type f -name '*.d.ts' -exec perl -i -pe "s/\.ts';/.js';/g" {} \;

      - name: Publish --dry-run
        run: npm publish --access=public --tag=next --dry-run

