name: Check



on: push



permissions:
  contents: read
  id-token: write



jobs:

  test-JSR:

    runs-on: ubuntu-24.04-arm
    timeout-minutes: 3

    steps:

      - name: Setup repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: v2

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno task spec --coverage --quiet --parallel

      - name: Run publish --dry-run
        run: deno publish --dry-run

      - name: Run codecov
        uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5.5.0
        with:
          files: coverage/lcov.info
          use_oidc: true

